# see https://github.com/ray-project/kuberay/tree/master/helm-chart/ray-cluster
# and https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/config.html
image:
  repository: rayproject/ray
  tag: 2.2.0-py39-cpu
  pullPolicy: IfNotPresent

head:
  enableInTreeAutoscaling: true
  rayStartParams:
    # don't use head node for scheduling
    # as per https://github.com/ray-project/kuberay/blob/master/docs/best-practice/worker-head-reconnection.md#best-practice
    num-cpus: 0
  resources:
    limits:
      cpu: "1"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "2G"

worker:
  minReplicas: 1
  maxReplicas: 10
  resources:
    limits:
      cpu: "2"
      memory: "2G"
    requests:
      cpu: "2"
      memory: "2G"
